services:
  api:
    image: api:prod
    build:
      context: .
      dockerfile: ./backend/api/Dockerfile
    entrypoint: bash -c "uv run fastapi run api/main.py --reload"
    env_file:
      - ./envs/shared_mcp.env
    ports:
      - 8000:8000
    volumes:
      - ./backend/api:/app/api
      - ./backend/api/.vscode/:/app/.vscode
      - ./backend/shared_mcp:/app/shared_mcp

  mcp:
    image: mcp:prod
    build:
      context: .
      dockerfile: ./backend/mcp/Dockerfile
    env_file:
      - ./envs/shared_mcp.env
    volumes:
      - ./backend/mcp:/app/mcp
      - ./backend/shared_mcp:/app/shared_mcp
